select
  fato_pessoal_ativo.id as pessoal_ativo_id,
	fato_pessoal_ativo.codigo_natureza_juridica,
	fato_pessoal_ativo.codigo_organizacao_1,
	fato_pessoal_ativo.codigo_organizacao_2,
	fato_pessoal_ativo.codigo_organizacao_3,
	fato_pessoal_ativo.codigo_organizacao_4,
	fato_pessoal_ativo.codigo_organizacao_5,
	fato_pessoal_ativo.codigo_organizacao_6,
	fato_pessoal_ativo.codigo_area_atuacao,
	fato_pessoal_ativo.codigo_escolaridade,
	fato_pessoal_ativo.codigo_faixa_etaria,
	fato_pessoal_ativo.codigo_forca_trabalho,
	fato_pessoal_ativo.valor_custo_pessoal_ativo,
  dim_pessoal_ativo.descricao_natureza_juridica,
	dim_pessoal_ativo.descricao_organizacao_1,
	dim_pessoal_ativo.descricao_organizacao_2,
	dim_pessoal_ativo.descricao_organizacao_3,
	dim_pessoal_ativo.descricao_organizacao_4,
	dim_pessoal_ativo.descricao_organizacao_5,
	dim_pessoal_ativo.descricao_organizacao_6,
	dim_pessoal_ativo.descricao_area_atuacao,
	dim_pessoal_ativo.descricao_escolaridade,
	dim_pessoal_ativo.descricao_faixa_etaria,
	dim_pessoal_ativo.codigo_sexo,
	fato_pessoal_ativo.ano_lancamento,
	fato_pessoal_ativo.mes_lancamento,
	fato_pessoal_ativo.mes_ano_lancamento
from {{ ref('dim_pessoal_ativo') }} dim_pessoal_ativo
inner join {{ ref('fato_pessoal_ativo') }} fato_pessoal_ativo on dim_pessoal_ativo.id = fato_pessoal_ativo.id