custos_stn:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 172.25.0.1
      user: postgres
      password: postgres
      port: 5432
      dbname: custos_stn
      schema: stg
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default